### ISSUE TITLE
Create separate Rails app for external DU site

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#173]
- [x] Copy pages served up by the static_pages_controller into a new Rails app
- [x] Use the new public members API (see #189) on /membership
- [x] Use the new application acceptance status API (see #190) on /membership
- [x] Link the login button to the new login page (see #192)
- [x] Set membership app URL in an initializer
