### ISSUE TITLE
Checklist of changes for when we have a physical space again

### ISSUE THREAD

**Issue by brittag** [doubleunion/arooo#538]
In the process of updating the DU website and app for our virtual-only status, we removed our address from the following places, so when we have a physical space again, we'll need to add the new address here:

- [ ] New member welcome email: https://github.com/doubleunion/arooo/blob/master/app/views/applications_mailer/approved.html.haml
- [x] On the external website, https://github.com/doubleunion/doubleunion-dot-org/blob/master/pages/visit.md + https://github.com/doubleunion/doubleunion-dot-org/blob/master/index.md

The current doorbell code is very specific to the Potrero space, so it will need to be updated and re-enabled (see https://github.com/doubleunion/arooo/issues/537).

Materials related to being a key member will also need to be updated and re-enabled. Materials that will need to be updated include:

- [ ] https://github.com/doubleunion/arooo/blob/master/app/views/member_status_mailer/new_key_member.html.haml

**Comment by brittag** [comment]
I set up a different issue for the key member emails (https://github.com/doubleunion/arooo/issues/610), so this would be closed by https://github.com/doubleunion/arooo/pull/612.
